name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download Source file
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - name: Build ewsba
        run: |
          GOOS=linux GOARCH=amd64 go build
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DOMAIN }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "ewsba"
          target: ${{ secrets.SITEPATH }}